apiVersion: v2
name: bitwardenrs
description: Unofficial Bitwarden compatible server written in Rust
type: application
version: 0.1.2
appVersion: 1.15.1
sources:
  - https://github.com/dani-garcia/bitwarden_rs